In [4]:
# Required imports.

import pandas as pd

In [21]:
# Load and read files.

train_filename = "Data_Train.csv"
test_filename = "Data_Test.csv"

train_df = pd.read_csv(train_filename)
test_df = pd.read_csv(test_filename)

train_df

                                                  STORY  SECTION
0     But the most painful was the huge reversal in ...        3
1     How formidable is the opposition alliance amon...        0
2     Most Asian currencies were trading lower today...        3
3     If you want to answer any question, click on �...        1
4     In global markets, gold prices edged up today ...        3
...                                                 ...      ...
7623  Karnataka has been a Congress bastion, but it ...        0
7624  The film, which also features Janhvi Kapoor, w...        2
7625  The database has been created after bringing t...        1
7626  The state, which has had an uneasy relationshi...        0
7627  Virus stars Kunchacko Boban, Tovino Thomas, In...        2

[7628 rows x 2 columns]

In [22]:
# Shuffle train data
train_df = train_df.sample(frac=1)
train_df

                                                  STORY  SECTION
3126  34 billion dollars which included more than 70...        2
7406  The reviewers' reports of broken screens went ...        1
5582  Actor Karen Gillan has opened up about James G...        2
882   The Left Front has nominated former Kolkata ma...        0
3483  We have spoken about a ?1 trillion irrigation ...        0
...                                                 ...      ...
5892  For example, using the DataCultr platform, fin...        1
7515  Google�s flood forecasting system uses machine...        1
5383  She appeared in Bichir�s directorial debut Un ...        2
5338  Tamil politics have long been associated with ...        0
7486  Voters queue up at various polling stations du...        0

[7628 rows x 2 columns]

In [23]:
training_fraction = 0.95
validatation_fration = 1 - training_fraction

train_data_len = len(train_df)
training_data_len = int(train_data_len * 0.95)
validation_data_len = train_data_len - training_data_len

print("all data: {}, train data: {}, validation data: {}".format(train_data_len, training_data_len, validation_data_len))

all data: 7628, train data: 7246, validation data: 382

In [28]:
training_dataset = train_df[0:training_data_len]
validation_dataset = train_df[training_data_len:]

In [29]:
training_dataset

                                                  STORY  SECTION
3126  34 billion dollars which included more than 70...        2
7406  The reviewers' reports of broken screens went ...        1
5582  Actor Karen Gillan has opened up about James G...        2
882   The Left Front has nominated former Kolkata ma...        0
3483  We have spoken about a ?1 trillion irrigation ...        0
...                                                 ...      ...
5873  From how she loves eating cheese, to fetching ...        2
399   The patent case is part of a two-year series o...        1
3188  A spokeswoman from Google declined to comment....        1
908   Besides, the residual maturity for amortisatio...        3
3602  If you�re a Note 5 user, you might now have a ...        1

[7246 rows x 2 columns]

In [30]:
validation_dataset

                                                  STORY  SECTION
2794  MUMBAI: A barrage of bad news have taken the s...        3
2460  Besides, e-voting will be a valid option for D...        3
3102  For fitness enthusiasts, there are numerous ap...        1
2294  It�s a wrap #saandkiaankh ?? Thank you all for...        2
4421  �People were angry with Vasundhara Raje and he...        0
...                                                 ...      ...
5892  For example, using the DataCultr platform, fin...        1
7515  Google�s flood forecasting system uses machine...        1
5383  She appeared in Bichir�s directorial debut Un ...        2
5338  Tamil politics have long been associated with ...        0
7486  Voters queue up at various polling stations du...        0

[382 rows x 2 columns]

In [33]:
X_training_dataset = training_dataset.drop("SECTION", axis=1)
X_training_dataset

                                                  STORY
3126  34 billion dollars which included more than 70...
7406  The reviewers' reports of broken screens went ...
5582  Actor Karen Gillan has opened up about James G...
882   The Left Front has nominated former Kolkata ma...
3483  We have spoken about a ?1 trillion irrigation ...
...                                                 ...
5873  From how she loves eating cheese, to fetching ...
399   The patent case is part of a two-year series o...
3188  A spokeswoman from Google declined to comment....
908   Besides, the residual maturity for amortisatio...
3602  If you�re a Note 5 user, you might now have a ...

[7246 rows x 1 columns]

In [34]:
Y_training_dataset = training_dataset["SECTION"]
Y_training_dataset

3126    2
7406    1
5582    2
882     0
3483    0
       ..
5873    2
399     1
3188    1
908     3
3602    1
Name: SECTION, Length: 7246, dtype: int64

In [1]:
import pandas as pd

In [2]:
# Load data return three datasets or dataframe : train_df, validation_df, and test_df
# Set train_fraction and validation fraction in range of (0, 1)
# Test fraction = 1 - train_frac - validation_frac
PATH = "Data_Train.csv"
def load_data(path, train_frac, validation_frac):
    df = pd.read_csv(path)
    len_df = len(df)
    len_train = int(train_frac * len_df)
    len_validation = int(validation_frac * len_df)
    len_test = len_df - len_train - len_validation
    train_df = df[0:len_train]
    validation_df = df[len_train:len_train+len_validation]
    test_df = df[(len_train+len_validation):]
    return train_df,validation_df,test_df

train_df,validation_df,test_df = load_data(PATH, 0.9, 0.05)
print("Load {} entries for training set, {} for validation set, {} for test set".format(len(train_df),\
                                                                                        len(validation_df),\
                                                                                        len(test_df)))

Load 6865 entries for training set, 381 for validation set, 382 for test set

In [3]:
# Return features (X) and label (Y) component of given dataset.
def prep_dataset(df, y_label):
    return df.drop("SECTION", axis=1), df["SECTION"]

x_train, y_train = prep_dataset(train_df, "SECTION")
x_valid, y_valid = prep_dataset(validation_df, "SECTION")
x_test, y_test = prep_dataset(test_df, "SECTION")

In [4]:
x_train

                                                  STORY
0     But the most painful was the huge reversal in ...
1     How formidable is the opposition alliance amon...
2     Most Asian currencies were trading lower today...
3     If you want to answer any question, click on �...
4     In global markets, gold prices edged up today ...
...                                                 ...
6860  But will this also mark an end to Jeremy Renne...
6861  On Checkout, people will be able to buy direct...
6862  India heads into its first fully-digital natio...
6863  So, you can say it is a balance of good recall...
6864  Here are some more photos of Srinish and Pearl...

[6865 rows x 1 columns]

In [5]:
train_df

                                                  STORY  SECTION
0     But the most painful was the huge reversal in ...        3
1     How formidable is the opposition alliance amon...        0
2     Most Asian currencies were trading lower today...        3
3     If you want to answer any question, click on �...        1
4     In global markets, gold prices edged up today ...        3
...                                                 ...      ...
6860  But will this also mark an end to Jeremy Renne...        2
6861  On Checkout, people will be able to buy direct...        1
6862  India heads into its first fully-digital natio...        0
6863  So, you can say it is a balance of good recall...        2
6864  Here are some more photos of Srinish and Pearl...        2

[6865 rows x 2 columns]

In [6]:
# Load GloVe model
GLOVE_PATH = "glove.6B.50d.txt"

def load_word_vectors(path):
    word_vectors = dict()
    f = open(path, encoding="utf-8")
    for line in f:
        values = line.split()
        word = values[0]
        word_numbers = values[1:]
        word_vectors[word] = word_numbers
    f.close()
    print("load {} word vectors.".format(len(word_vectors)))
    return word_vectors

word_vectors = load_word_vectors(GLOVE_PATH)
# word_vectors

load 400000 word vectors.

In [7]:
# General setup
EMBEDDING_DIM = 50
FILTER_SIZES = [3,4]
NUM_FILTERS = 100
DROP = 0.4

In [48]:
from sklearn.model_selection import train_test_split
def load_split_data(path):
    df = pd.read_csv(path)
    X = df.iloc[:,0]
    Y = df.iloc[:,1]

    X_training, X_validation, Y_training, Y_validation = train_test_split(X, Y, test_size=0.1, random_state=123)
    X_validation, X_test, Y_validation, Y_test = train_test_split(X_validation, Y_validation, test_size=0.5, random_state=123)
    
    return X_training, X_validation, X_test, Y_training, Y_validation, Y_test

X_training, X_validation, X_test, Y_training, Y_validation, Y_test = load_split_data(PATH)

In [49]:
X_training

1088    Bloomberg reported on 22 March that the treasu...
1472    Facebook, WhatsApp and Twitter have overhauled...
4010    The donors bought 1,459 electoral bonds of den...
66      �In another tweet, he wrote, �#AvengersEndgame...
7489    New Delhi: We profile two enterprise tech star...
                              ...
4060    "It's why we're seeing Indian artists connect ...
1346    A similar battle is expected in the Muzaffarna...
3454    Huawei Mate 20 lineup consists of a radial cam...
7533    Achievements of PM Modi, the nation�s growth a...
3582    At the back the Redmi Note 6 Pro sports the sa...
Name: STORY, Length: 6865, dtype: object

In [50]:
# CNN Implementation imports
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding

# Gensim
import gensim
from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
from gensim.models.keyedvectors import KeyedVectors

In [52]:
NUM_WORDS = 30000

tokenizer_train = Tokenizer(num_words=NUM_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\'')
tokenizer_valid = Tokenizer(num_words=NUM_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\'')

# Get values from training dataframe
tokenizer_train.fit_on_texts(X_training)

# Get values from validation dataframe
tokenizer_valid.fit_on_texts(X_validation)

# Count unique tokens
word_index_train = tokenizer_train.word_index
word_index_valid = tokenizer_valid.word_index
print('Found {} unique tokens in training data.'.format(len(word_index_train)))
print('Found {} unique tokens in validation data.'.format(len(word_index_valid)))

Found 35231 unique tokens in training data.
Found 7872 unique tokens in validation data.

In [23]:
x_train_values = x_train.values.tolist()
x_valid_values = x_valid.values.tolist()

sequences_train = tokenizer.texts_to_sequences(x_train_values)
sequences_valid = tokenizer.texts_to_sequences(x_valid_values)

In [24]:
sequences_train

[[44],
 [45],
 [46],
 [47],
 [48],
 [49],
 [50],
 [51],
 [52],
 [53],
 [54],
 [55],
 [56],
 [57],
 [58],
 [59],
 [60],
 [61],
 [62],
 [63],
 [64],
 [65],
 [66],
 [67],
 [6],
 [68],
 [69],
 [70],
 [71],
 [72],
 [73],
 [74],
 [75],
 [76],
 [77],
 [78],
 [79],
 [80],
 [81],
 [82],
 [83],
 [84],
 [85],
 [86],
 [87],
 [88],
 [89],
 [90],
 [91],
 [92],
 [93],
 [94],
 [95],
 [96],
 [97],
 [98],
 [99],
 [100],
 [101],
 [102],
 [103],
 [104],
 [105],
 [106],
 [107],
 [108],
 [109],
 [110],
 [111],
 [112],
 [113],
 [114],
 [115],
 [116],
 [117],
 [118],
 [119],
 [120],
 [121],
 [122],
 [123],
 [124],
 [125],
 [126],
 [127],
 [128],
 [129],
 [130],
 [131],
 [132],
 [133],
 [134],
 [135],
 [136],
 [137],
 [138],
 [139],
 [140],
 [141],
 [142],
 [143],
 [144],
 [145],
 [146],
 [147],
 [148],
 [149],
 [7],
 [150],
 [151],
 [152],
 [153],
 [154],
 [155],
 [156],
 [157],
 [158],
 [159],
 [160],
 [161],
 [162],
 [163],
 [164],
 [165],
 [166],
 [167],
 [168],
 [169],
 [170],
 [171],
 [172],
 [173],
 [174],
 [175],
 [176],
 [177],
 [178],
 [179],
 [180],
 [181],
 [182],
 [183],
 [184],
 [185],
 [186],
 [187],
 [188],
 [189],
 [190],
 [191],
 [192],
 [193],
 [194],
 [195],
 [196],
 [197],
 [198],
 [199],
 [200],
 [201],
 [202],
 [203],
 [204],
 [205],
 [206],
 [207],
 [208],
 [209],
 [210],
 [211],
 [212],
 [213],
 [214],
 [215],
 [216],
 [217],
 [218],
 [219],
 [220],
 [221],
 [222],
 [223],
 [224],
 [225],
 [226],
 [227],
 [228],
 [229],
 [230],
 [231],
 [232],
 [8],
 [233],
 [234],
 [235],
 [236],
 [1],
 [237],
 [238],
 [239],
 [240],
 [241],
 [242],
 [243],
 [244],
 [245],
 [246],
 [247],
 [248],
 [249],
 [250],
 [251],
 [252],
 [253],
 [254],
 [255],
 [256],
 [257],
 [258],
 [259],
 [260],
 [261],
 [262],
 [263],
 [264],
 [265],
 [266],
 [267],
 [268],
 [269],
 [270],
 [271],
 [272],
 [273],
 [274],
 [275],
 [276],
 [277],
 [278],
 [279],
 [280],
 [281],
 [282],
 [283],
 [284],
 [285],
 [286],
 [287],
 [288],
 [289],
 [290],
 [291],
 [292],
 [9],
 [293],
 [2],
 [294],
 [295],
 [296],
 [297],
 [298],
 [299],
 [300],
 [301],
 [302],
 [303],
 [304],
 [305],
 [306],
 [307],
 [308],
 [309],
 [310],
 [311],
 [312],
 [313],
 [314],
 [315],
 [316],
 [317],
 [318],
 [319],
 [320],
 [321],
 [322],
 [323],
 [324],
 [325],
 [326],
 [327],
 [328],
 [329],
 [330],
 [331],
 [332],
 [333],
 [334],
 [335],
 [336],
 [337],
 [338],
 [339],
 [340],
 [341],
 [342],
 [343],
 [344],
 [10],
 [345],
 [346],
 [347],
 [348],
 [349],
 [350],
 [351],
 [352],
 [353],
 [354],
 [355],
 [356],
 [357],
 [358],
 [359],
 [360],
 [361],
 [362],
 [363],
 [364],
 [365],
 [366],
 [367],
 [368],
 [369],
 [370],
 [371],
 [372],
 [373],
 [374],
 [375],
 [376],
 [377],
 [378],
 [379],
 [380],
 [381],
 [382],
 [383],
 [384],
 [6],
 [385],
 [386],
 [387],
 [388],
 [389],
 [390],
 [391],
 [392],
 [393],
 [394],
 [395],
 [396],
 [397],
 [398],
 [399],
 [400],
 [401],
 [402],
 [403],
 [404],
 [405],
 [406],
 [407],
 [408],
 [409],
 [410],
 [411],
 [412],
 [413],
 [414],
 [415],
 [416],
 [417],
 [418],
 [419],
 [420],
 [421],
 [422],
 [423],
 [424],
 [425],
 [426],
 [427],
 [428],
 [429],
 [430],
 [431],
 [432],
 [433],
 [434],
 [435],
 [436],
 [437],
 [438],
 [439],
 [440],
 [441],
 [442],
 [443],
 [444],
 [445],
 [446],
 [447],
 [448],
 [449],
 [450],
 [451],
 [452],
 [453],
 [454],
 [455],
 [456],
 [457],
 [458],
 [459],
 [460],
 [461],
 [462],
 [463],
 [464],
 [465],
 [466],
 [467],
 [468],
 [469],
 [470],
 [471],
 [472],
 [473],
 [474],
 [475],
 [476],
 [3],
 [477],
 [478],
 [479],
 [480],
 [481],
 [482],
 [483],
 [484],
 [485],
 [486],
 [487],
 [488],
 [489],
 [490],
 [491],
 [492],
 [493],
 [494],
 [495],
 [496],
 [497],
 [1],
 [498],
 [499],
 [500],
 [501],
 [502],
 [503],
 [504],
 [505],
 [506],
 [507],
 [508],
 [509],
 [510],
 [511],
 [512],
 [513],
 [514],
 [515],
 [516],
 [517],
 [518],
 [519],
 [520],
 [521],
 [522],
 [523],
 [524],
 [525],
 [526],
 [527],
 [528],
 [529],
 [530],
 [531],
 [532],
 [533],
 [534],
 [535],
 [11],
 [536],
 [537],
 [538],
 [539],
 [540],
 [541],
 [542],
 [543],
 [544],
 [545],
 [546],
 [547],
 [548],
 [549],
 [550],
 [551],
 [552],
 [553],
 [554],
 [555],
 [556],
 [557],
 [558],
 [559],
 [560],
 [561],
 [562],
 [563],
 [564],
 [565],
 [566],
 [567],
 [568],
 [569],
 [570],
 [571],
 [572],
 [573],
 [574],
 [575],
 [576],
 [577],
 [578],
 [579],
 [580],
 [581],
 [582],
 [583],
 [584],
 [585],
 [586],
 [587],
 [588],
 [589],
 [590],
 [591],
 [592],
 [593],
 [594],
 [595],
 [596],
 [597],
 [598],
 [599],
 [600],
 [601],
 [602],
 [603],
 [604],
 [605],
 [12],
 [606],
 [607],
 [608],
 [609],
 [610],
 [611],
 [612],
 [613],
 [614],
 [615],
 [616],
 [617],
 [618],
 [3],
 [619],
 [620],
 [621],
 [622],
 [623],
 [624],
 [625],
 [626],
 [627],
 [628],
 [629],
 [630],
 [631],
 [632],
 [633],
 [634],
 [635],
 [636],
 [637],
 [638],
 [639],
 [640],
 [641],
 [642],
 [643],
 [644],
 [645],
 [646],
 [647],
 [648],
 [649],
 [650],
 [651],
 [652],
 [653],
 [654],
 [655],
 [656],
 [657],
 [658],
 [659],
 [660],
 [661],
 [662],
 [663],
 [664],
 [665],
 [666],
 [667],
 [668],
 [669],
 [670],
 [671],
 [672],
 [673],
 [674],
 [675],
 [676],
 [677],
 [678],
 [679],
 [680],
 [681],
 [682],
 [683],
 [684],
 [685],
 [686],
 [687],
 [688],
 [689],
 [690],
 [691],
 [692],
 [693],
 [694],
 [695],
 [696],
 [697],
 [698],
 [699],
 [700],
 [701],
 [702],
 [703],
 [704],
 [705],
 [706],
 [707],
 [708],
 [709],
 [710],
 [711],
 [712],
 [713],
 [714],
 [715],
 [716],
 [717],
 [718],
 [719],
 [720],
 [721],
 [722],
 [723],
 [724],
 [725],
 [726],
 [727],
 [728],
 [729],
 [730],
 [731],
 [732],
 [733],
 [734],
 [735],
 [736],
 [737],
 [738],
 [739],
 [740],
 [741],
 [742],
 [743],
 [744],
 [745],
 [746],
 [747],
 [748],
 [749],
 [750],
 [751],
 [752],
 [753],
 [754],
 [755],
 [756],
 [757],
 [13],
 [758],
 [759],
 [760],
 [761],
 [762],
 [763],
 [764],
 [765],
 [766],
 [767],
 [768],
 [769],
 [770],
 [771],
 [772],
 [773],
 [774],
 [775],
 [776],
 [777],
 [778],
 [779],
 [780],
 [781],
 [782],
 [783],
 [784],
 [785],
 [786],
 [2],
 [787],
 [788],
 [789],
 [790],
 [791],
 [792],
 [793],
 [794],
 [795],
 [796],
 [797],
 [798],
 [799],
 [800],
 [801],
 [802],
 [803],
 [804],
 [805],
 [806],
 [807],
 [808],
 [809],
 [810],
 [811],
 [812],
 [813],
 [814],
 [815],
 [816],
 [817],
 [818],
 [819],
 [820],
 [821],
 [822],
 [823],
 [824],
 [825],
 [826],
 [827],
 [828],
 [829],
 [830],
 [831],
 [832],
 [833],
 [834],
 [835],
 [836],
 [837],
 [838],
 [839],
 [840],
 [841],
 [842],
 [843],
 [844],
 [845],
 [846],
 [847],
 [848],
 [849],
 [850],
 [851],
 [852],
 [853],
 [854],
 [855],
 [856],
 [857],
 [858],
 [859],
 [860],
 [861],
 [862],
 [863],
 [1],
 [864],
 [865],
 [866],
 [867],
 [868],
 [869],
 [870],
 [871],
 [872],
 [873],
 [874],
 [875],
 [876],
 [877],
 [878],
 [879],
 [880],
 [881],
 [882],
 [883],
 [884],
 [885],
 [886],
 [887],
 [888],
 [889],
 [890],
 [891],
 [892],
 [893],
 [894],
 [895],
 [896],
 [897],
 [898],
 [899],
 [900],
 [901],
 [902],
 [903],
 [904],
 [905],
 [906],
 [907],
 [908],
 [909],
 [910],
 [911],
 [912],
 [913],
 [914],
 [915],
 [916],
 [917],
 [918],
 [919],
 [920],
 [921],
 [922],
 [923],
 [924],
 [925],
 [926],
 [927],
 [928],
 [929],
 [930],
 [931],
 [932],
 [933],
 [934],
 [935],
 [936],
 [937],
 [938],
 [939],
 [940],
 [941],
 [942],
 [943],
 [944],
 [945],
 [946],
 [947],
 [948],
 [949],
 [950],
 [951],
 [952],
 [953],
 [954],
 [955],
 [956],
 [957],
 [958],
 [959],
 [960],
 [961],
 [962],
 [963],
 [964],
 [965],
 [966],
 [967],
 [968],
 [969],
 [970],
 [971],
 [972],
 [973],
 [974],
 [975],
 [10],
 [976],
 [977],
 [978],
 [979],
 [980],
 [981],
 [982],
 [983],
 [984],
 [985],
 [986],
 [987],
 [988],
 [989],
 [990],
 [991],
 [992],
 [993],
 [994],
 [995],
 [996],
 [997],
 [998],
 [999],
 [1000],
 [1001],
 [1002],
 [1003],
 [1004],
 [1005],
 [1006],
 [1007],
 [1008],
 [1009],
 [1010],
 [1011],
 [1012],
 [1013],
 [1014],
 [1015],
 [1016],
 [1017],
 [1018],
 [1019],
 [1020],
 [1021],
 [1022],
 [1023],
 [1024],
 [1025],
 [1026],
 ...]

In [25]:
sequences_valid

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [1727],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [23],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [2738],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [ ]:
EMBEDDING_DIM = 50
sequence_length = X_train.shape[1]
filter_sizes = [3,4]
num_filters = 100
drop = 0.4

inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)
reshape = Reshape((sequence_length,EMBEDDING_DIM,1))(embedding)

conv_0 = Conv2D(num_filters, (filter_sizes[0], EMBEDDING_DIM),activation='relu',kernel_regularizer=regularizers.l2(0.01))(reshape)
conv_1 = Conv2D(num_filters, (filter_sizes[1], EMBEDDING_DIM),activation='relu',kernel_regularizer=regularizers.l2(0.01))(reshape)

maxpool_0 = MaxPooling2D((sequence_length - filter_sizes[0] + 1, 1), strides=(1,1))(conv_0)
maxpool_1 = MaxPooling2D((sequence_length - filter_sizes[1] + 1, 1), strides=(1,1))(conv_1)

merged_tensor = concatenate([maxpool_0, maxpool_1], axis=1)
flatten = Flatten()(merged_tensor)
reshape = Reshape((2*num_filters,))(flatten)
dropout = Dropout(drop)(flatten)
conc = Dense(40)(dropout)
output = Dense(units=6, activation='sigmoid',kernel_regularizer=regularizers.l2(0.01))(conc)

# this creates a model that includes
model = Model(inputs, output)